name: to_do_list
description: To Do List Manager


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  provider: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: MuktaVaani
      fonts:
        - asset: fonts/MuktaVaani-Regular.ttf